CREATE DATABASE IF NOT EXISTS readme
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE readme;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  registration_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(128) NOT NULL UNIQUE,
  login VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS posts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(128) NOT NULL,
  text_content VARCHAR(255) NULL,
  quote VARCHAR(128) NULL,
  quote_author VARCHAR(128) NULL,
  image VARCHAR(255) NULL,
  video VARCHAR(255) NULL,
  link VARCHAR(255) NULL,
  count_views INT NOT NULL DEFAULT 0,
  user_id INT NOT NULL,
  content_type INT NOT NULL,
  hashtag INT,
  FOREIGN KEY(user_id) REFERENCES users(id),
  FOREIGN KEY(content_type) REFERENCES content_types(id),
  FOREIGN KEY(hashtag) REFERENCES hashtags(id)
);

CREATE TABLE IF NOT EXISTS comments (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  text_content VARCHAR(128) NOT NULL,
  author INT NOT NULL,
  post INT NOT NULL,
  FOREIGN KEY(author) REFERENCES users(id),
  FOREIGN KEY(post) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS likes (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user INT NOT NULL,
  post INT NOT NULL,
  FOREIGN KEY(user) REFERENCES users(id),
  FOREIGN KEY(post) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sender INT NOT NULL,
  recipient INT NOT NULL,
  FOREIGN KEY(sender) REFERENCES users(id),
  FOREIGN KEY(recipient) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS messages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  text_content VARCHAR(128) NOT NULL,
  sender INT NOT NULL,
  recipient INT NOT NULL,
  FOREIGN KEY(sender) REFERENCES users(id),
  FOREIGN KEY(recipient) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS hashtags (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS content_types (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL UNIQUE,
  icon VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS posts_hashtags (
  post_id INT NOT NULL,
  hashtag_id INT NOT NULL,
  FOREIGN KEY(post_id) REFERENCES posts(id),
  FOREIGN KEY(hashtag_id) REFERENCES hashtags(id)
);
